# Generated by Django 4.0.3 on 2022-04-06 18:36

import blog_app.profile_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0009_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=20, validators=[blog_app.profile_app.validators.validate_letters_only]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=20, validators=[blog_app.profile_app.validators.validate_letters_only]),
        ),
    ]
