# Generated by Django 4.0.3 on 2022-03-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_category', '0002_alter_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
