# Generated by Django 4.0.3 on 2022-03-18 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0003_post_created_on_post_updated_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blog_post.post'),
            preserve_default=False,
        ),
    ]
